### ISSUE TITLE
Example how to running  the  Docker image

### ISSUE THREAD

**Issue by vtrmantovani** [getsandbox/worker-cli#46]
Hi, could you please show an example of how to run the docker image? 
I've tried to find an example on the docker hub or on the repo, but unfortunately, I couldn't find an example of how to use it.

Currently, I've tried this: 

```shellscript
docker pull getsandbox/worker-cli:2.0.5 && docker run getsandbox/worker-cli:2.0.5
```

But the output was: 
```shellscript
2.0.5: Pulling from getsandbox/worker-cli
Digest: sha256:4830bc106fd656a0c69d01a46f5fc0130949ab43737cf9dd8cabf1beeedfb865
Status: Image is up to date for getsandbox/worker-cli:2.0.5
docker.io/getsandbox/worker-cli:2.0.5
Error starting Micronaut server: Bean definition [com.sandbox.worker.cli.CLIRequestServer] could not be loaded: Failed to inject value for field [environment] of class: com.sandbox.worker.cli.CLIRequestServer

Message: Error setting field value: No field 'environment' found for type: com.sandbox.worker.cli.CLIRequestServer

io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [com.sandbox.worker.cli.CLIRequestServer] could not be loaded: Failed to inject value for field [environment] of class: com.sandbox.worker.cli.CLIRequestServer

Message: Error setting field value: No field 'environment' found for type: com.sandbox.worker.cli.CLIRequestServer

	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1380)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2568)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:202)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:188)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at com.sandbox.worker.cli.AppMain.start(AppMain.java:14)
	at com.sandbox.worker.cli.CLIMain.main(CLIMain.java:47)
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [environment] of class: com.sandbox.worker.cli.CLIRequestServer

Message: Error setting field value: No field 'environment' found for type: com.sandbox.worker.cli.CLIRequestServer

	at io.micronaut.context.AbstractBeanDefinition.injectBeanField(AbstractBeanDefinition.java:748)
	at com.sandbox.worker.cli.$CLIRequestServerDefinition.injectBean(Unknown Source)
	at com.sandbox.worker.cli.$CLIRequestServerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1714)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2428)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2015)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1378)
	... 7 common frames omitted
Caused by: java.lang.NoSuchFieldError: No field 'environment' found for type: com.sandbox.worker.cli.CLIRequestServer
	at io.micronaut.core.reflect.ReflectionUtils.lambda$getRequiredField$2(ReflectionUtils.java:301)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.micronaut.core.reflect.ReflectionUtils.getRequiredField(ReflectionUtils.java:301)
	at io.micronaut.context.DefaultFieldInjectionPoint.getField(DefaultFieldInjectionPoint.java:117)
	at io.micronaut.context.DefaultFieldInjectionPoint.set(DefaultFieldInjectionPoint.java:127)
	at io.micronaut.context.AbstractBeanDefinition.injectBeanField(AbstractBeanDefinition.java:742)
	... 13 common frames omitted
Shutting down..
```

**Comment by nhoughto** [comment]
thanks for the info, let me look into it and get back. Will likely create a proper set of CI tests for this too.

**Comment by nhoughto** [comment]
Fixed

**Comment by nhoughto** [comment]
Ah and to answer the actual question:
`docker run -v $(pwd):/base -it getsandbox/worker-cli:latest`

Where `$(pwd)` or whatever you are mounting is your sandbox definition.
