### ISSUE TITLE
NoClassDefFoundError from fat jar

### ISSUE THREAD

**Issue by brockwmills** [getsandbox/worker-cli#47]
Fat jar isn't fat enough? 

Running a trivial mock fails to load javax.activation.MimetypesFileTypeMap

mock:

```javascript
Sandbox.define('/consent', 'GET', function(req, res){
    return res.json(200, {"hello" : "there"})
});
```

```
$ java -jar worker-cli_worker-cli-latest.jar --watch
Sandbox ready (build: v? runtime: VERSION_3) --  Running on port: 8080, metadata on port: disabled, reading from path: 'C:\Users\brock\Development\ecm\mocks', took: 3874ms
** Error processing request for GET /consents - Invalid route

>> HTTP GET /consent  (Matched route '/consent')
>> Headers: {Accept=*/*, content-length=0, Host=localhost:8080, User-Agent=curl/7.73.0}
>> No body found
Exception in catch-all
java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
        at com.sandbox.worker.core.js.models.WorkerHttpRequest.<clinit>(WorkerHttpRequest.java:50)
        at com.sandbox.worker.core.services.RuntimeRequestConverter.fromInstanceHttpRequest(RuntimeRequestConverter.java:11)
        at com.sandbox.worker.core.js.ProcessRequestExecutor.doExecute(ProcessRequestExecutor.java:69)
        at com.sandbox.worker.core.js.ProcessRequestExecutor.doExecute(ProcessRequestExecutor.java:27)
        at com.sandbox.worker.core.js.AbstractJSExecutor.execute(AbstractJSExecutor.java:16)
        at com.sandbox.worker.core.server.WorkerRequestRunnable.doRun(WorkerRequestRunnable.java:46)
        at com.sandbox.worker.core.js.models.WorkerRunnable.call(WorkerRunnable.java:32)
        at com.sandbox.worker.core.js.models.WorkerRunnable.call(WorkerRunnable.java:9)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.activation.MimetypesFileTypeMap
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 12 common frames omitted
Error processing request - Caught error
```

**Comment by nhoughto** [comment]
Gotta run it on Java 8.

**Comment by brockwmills** [comment]
No school like the old school eh?
